---
- name: Install MacOS Packages
  hosts: localhost
  become: false
  vars:
    mas_installed_app_ids:
      - 497799835 # Xcode
    homebrew_cask_apps: 
      - airflow
      - bitwarden
      - balenaetcher
      - docker
      - firefox
      - google-chrome
      - handbrake
      - home-assistant
      - imageoptim
      - mullvadvpn
      - raspberry-pi-imager
      - remarkable
      - telegram-desktop
      - visual-studio-code
      - vlc
    homebrew_installed_packages:
      - ffmpeg
      - flux
      - get_iplayer
      - git
      - helm
      - jq
      - kubectl
      - macvim
      - mutt
      - neofetch
      - transmission-cli
      - nmap
      - rsync
      - sqlite
      - watch
      - wget
      - youtube-dl
      - yq
      - mas
      - pv
      - cowsay
    configure_dock: true
    dockitems_remove:
      - Launchpad
      - TV
  roles:
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.mas