---
- name: Install MacOS Packages for work
  hosts: localhost
  vars:
    homebrew_upgrade_all_packages: true
    configure_dotfiles: false
    homebrew_taps:
      - homebrew/core
      - homebrew/cask-fonts
    mas_installed_apps:
      - {id: 937984704, name: "Amphetamine"}
      - {id: 1289583905, name: "Pixelmator Pro"}
      - {id: 1591303229, name: "Vinegar - Tube Cleaner"}
      - {id: 1352778147, name: "Bitwarden"}
      - {id: 457622435, name: "Yoink"}
      - {id: 1502839586 , name: "Hand Mirror"}
      - {id: 1091189122, name: "Bear"}
      - {id: 775737590, name: "iA Writer"}
    pip_packages:
      - mkdocs
    homebrew_cask_apps: 
      - iterm2
      - docker
      - firefox
      - google-chrome
      - home-assistant
      - imageoptim
      - remarkable
      - obsidian
      - telegram-desktop
      - visual-studio-code
      - font-hack-nerd-font
      - font-3270-nerd-font
      - authy
      - modern-csv
    homebrew_installed_packages:
      - ffmpeg
      - flux
      - git
      - helm
      - jq
      - kubectl
      - macvim
      - mutt
      - neofetch
      - terraform
      - cdrtools
      - nmap
      - rsync
      - sqlite
      - watch
      - wget
      - yq
      - mas
      - pv
      - cowsay
      - starship
    configure_dock: true
    dockitems_remove:
      - Launchpad
      - TV
      - Maps
      - FaceTime
      - Freeform
      - Pages
      - Safari
      - Contacts
      - Reminders
      - Podcasts
      - App Store
      - Music
      - Notes
      - Photos
      - Messages
      - System Preferences
    dockitems_persist:
      - name: Mail
        path: "/Applications/Mail.app/"
        pos: 1
      - name: Calendar
        path: "/Applications/Calendar.app/"
        pos: 2
      - name: Microsoft Outlook
        path: "/Applications/Microsoft Outlook.app/"
        pos: 3
      - name: Slack
        path: "/Applications/Slack.app/"
        pos: 4
      - name: Firefox
        path: "/Applications/Firefox.app/"
        pos: 5
      - name: iTerm
        path: "/Applications/iTerm.app/"
        pos: 6
  roles:
    - geerlingguy.mac.mas
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.dock
